name: flutter_application
description: "A new Flutter project."
publish_to: "none"

version: 2.0.4

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  network_info_plus: ^5.0.3
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  capped_progress_indicator: ^0.0.2
  connectivity_plus: ^6.0.3
  google_fonts: ^6.2.1
  android_id: ^0.4.0
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.3+2
  cool_alert_two: ^0.1.0
  quickalert: ^1.1.0
  line_awesome_flutter: ^3.0.1
  animated_theme_switcher: ^2.0.10
  fancy_bottom_navigation_plus: ^1.0.3
  fancy_bottom_navigation_2: ^0.3.5
  loading_indicator: ^3.1.1
  flutter_spinkit: ^5.2.1
  awesome_snackbar_content: ^0.1.3
  flutter_countdown_timer: ^4.1.0
  percent_indicator: ^4.2.2
  lottie: ^2.7.0
  toast: ^0.3.0
  ariyanpay: ^0.0.5
  platform_device_id_web: ^1.0.0
  device_info: ^2.0.0
  platform_device_id_platform_interface: ^1.0.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  in_app_update: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  babstrap_settings_screen: ^0.1.6
  settings_ui: ^2.0.2
  flutter_share: ^2.0.0
  path_provider: ^2.1.4
  flutter_internet_speed_test: ^1.0.1
  webview_flutter: ^2.8.0
  onesignal_flutter: ^5.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/banners/

  fonts:
    - family: Bangla
      fonts:
        - asset: assets/fonts/Bangla.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
