name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  network_info_plus: ^5.0.3
  device_info_plus: ^10.1.0
  http: ^1.2.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  capped_progress_indicator: ^0.0.2
  connectivity_plus: ^6.0.3
  google_fonts: ^6.2.1
  android_id: ^0.4.0
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.3+2
  cool_alert_two: ^0.1.0
  quickalert: ^1.1.0
  permission_handler: ^11.3.1
  line_awesome_flutter: ^3.0.1
  animated_theme_switcher: ^2.0.10
  fancy_bottom_navigation_plus: ^1.0.3
  fancy_bottom_navigation_2: ^0.3.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/PopRobotopins-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 800
          style: italic



       

